version: "3.7"
services:
  app:
    image: webbookstore
    build:
      # args:
      #   user: youraccount
      #   uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: appwbs
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - wbs
  db:
    image: mysql:8.0
    container_name: dbwbs
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    networks:
      - wbs
  nginx:
    image: nginx:alpine
    container_name: nginxwbs
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
      - ./docker-compose/ssl:/etc/nginx/ssl
    networks:
      - wbs
networks:
  wbs:
    driver: bridge